# Generated by Django 6.0.5 on 2026-06-02 08:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100, unique=True, verbose_name='Název země')),
                ('kod', models.CharField(max_length=3, unique=True, verbose_name='Kód země (např. GBR)')),
                ('vlajka_url', models.URLField(blank=True, null=True, verbose_name='URL adresa vlajky (např. z Wikipedie)')),
            ],
            options={
                'verbose_name': 'Země',
                'verbose_name_plural': 'Země',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100, unique=True, verbose_name='Název týmu')),
                ('sef', models.CharField(max_length=100, verbose_name='Šéf týmu')),
                ('barva_hex', models.CharField(default='#FF0000', max_length=7, validators=[django.core.validators.RegexValidator(message='Zadejte platný HEX kód (např. #FF0000)', regex='^#[a-fA-F0-9]{6}$')], verbose_name='HEX barva týmu')),
                ('zeme', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='f1_app.country', verbose_name='Licence (Země)')),
            ],
            options={
                'verbose_name': 'Tým',
                'verbose_name_plural': 'Týmy',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100, verbose_name='Jméno jezdce')),
                ('cislo', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Startovní číslo')),
                ('zeme', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='f1_app.country', verbose_name='Národnost')),
                ('tym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jezdci', to='f1_app.team', verbose_name='Tým')),
            ],
            options={
                'verbose_name': 'Jezdec',
                'verbose_name_plural': 'Jezdci',
                'ordering': ['cislo'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100, verbose_name='Název okruhu')),
                ('delka_km', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Délka okruhu (km)')),
                ('zeme', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='f1_app.country', verbose_name='Země')),
            ],
            options={
                'verbose_name': 'Okruh',
                'verbose_name_plural': 'Okruhy',
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(verbose_name='Datum závodu')),
                ('nejrychlejsi_kolo_cas', models.CharField(blank=True, max_length=10, null=True, verbose_name='Čas nejrychlejšího kola (např. 1:23.456)')),
                ('nejrychlejsi_kolo_jezdec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='f1_app.driver', verbose_name='Jezdec s nejrychlejším kolem')),
                ('okruh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1_app.track', verbose_name='Závodní okruh')),
            ],
            options={
                'verbose_name': 'Závod',
                'verbose_name_plural': 'Závody',
                'ordering': ['datum'],
                'constraints': [models.UniqueConstraint(fields=('okruh', 'datum'), name='unique_race_per_day')],
            },
        ),
    ]
