# Generated by Django 6.0.5 on 2026-06-13 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='vitez',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vyhrane_zavody', to='f1_app.driver', verbose_name='Vítěz závodu'),
        ),
        migrations.AlterField(
            model_name='race',
            name='nejrychlejsi_kolo_jezdec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nejrychlejsi_kola', to='f1_app.driver', verbose_name='Jezdec s nejrychlejším kolem'),
        ),
    ]
